Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -1,4 +1,4 @@
-name: Manual Android Build
+name: Manual Android Build (may work now)
 
 on:
   push:
@@ -11,51 +11,39 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    # Checkout o código do repositório
     - name: Checkout code
       uses: actions/checkout@v3
 
-    # Instalar dependências e configurar Android SDK
     - name: Install dependencies and Android SDK
       run: |
-        # Atualizar e instalar dependências necessárias
         sudo apt-get update
         sudo apt-get install -y openjdk-11-jdk wget zip unzip
 
-        # Baixar e configurar o Android SDK Command Line Tools
         wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
         mkdir -p $HOME/android-sdk/cmdline-tools
         unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
         mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
 
-        # Configurar variáveis de ambiente
         export ANDROID_HOME=$HOME/android-sdk
         export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.0:$PATH
 
-        # Aceitar licenças e instalar Build Tools
         yes | sdkmanager --licenses
         sdkmanager "platform-tools" "platforms;android-30" "build-tools;33.0.0"
 
-        # Instala APKTOOL
         wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
         wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.8.1.jar -O /usr/local/bin/apktool.jar
         chmod +rwx /usr/local/bin/apktool
 
-        # Verificar se os Build Tools foram instalados corretamente
-        echo "Verificando instalação de Build Tools:"
-        ls -l $ANDROID_HOME/build-tools/33.0.0 || echo "Build Tools não encontrados!"
+        echo "Verifing Build Tools:"
+        ls -l $ANDROID_HOME/build-tools/33.0.0 || echo "Build Tools not found!"
 
-    # Compilar o projeto
     - name: Compile project
       run: |
-        # Compilar APK com apktool
         apktool b . -o cstrike_unsigned.apk
-        # Assinar o APK com apksigner
         # apksigner sign --ks my-release-key.jks --ks-key-alias my-key-alias --ks-pass pass:whyareyouhere --key-pass pass:nopee11 --out cstrike_signed.apk cstrike_unsigned.apk
 
-    # Fazer upload do APK assinado como artefato
     - name: Upload APK
       uses: actions/upload-artifact@v3
       with:
-        name: cstrike-unsigned-apk
-        path: cstrike_unsigned.apk
+        name: cstrike-unsigned-new-apk
+        path: cstrike_unsigned-new.apk
